### ISSUE TITLE
Uncaught TypeError: Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by alberto-chiarini** [James-Yu/Atom-LaTeX#34] opened 2017-03-28 10:43 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [atom-latex](https://github.com/James-Yu/Atom-LaTeX) package 0.7.4

### Stack Trace

Uncaught TypeError: Cannot read property 'file' of undefined

```
At C:\Users\Alberto\.atom\packages\atom-latex\lib\manager.coffee:15

TypeError: Cannot read property 'file' of undefined
    at Manager.module.exports.Manager.loadLocalCfg (/packages/atom-latex/lib/manager.coffee:15:5)
    at Manager.module.exports.Manager.isTexFile (/packages/atom-latex/lib/manager.coffee:35:20)
    at /packages/atom-latex/lib/main.coffee:58:28
    at editorsMinimaps.forEach (/packages/minimap/lib/main.js:377:51)
    at Map.forEach (native)
    at Main.observeMinimaps (/packages/minimap/lib/main.js:377:28)
    at Object.lazyLoad (/packages/atom-latex/lib/main.coffee:54:33)
    at /packages/atom-latex/lib/main.coffee:16:30
```

### Commands

```
```

### Non-Core Packages

```
atom-latex 0.7.4 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
minimap 4.26.8 
```

**Comment by jasm32851** [comment] 2017-04-27 21:19
I keep getting this error. How did you fix it?

**Comment by ashthespy** [comment] 2017-04-28 10:30
Hi, 
Could you provide more details on your project structure?
Do you have multiple Atom projects open?

**Comment by jasm32851** [comment] 2017-04-28 13:53
Sure, I'm editing only the LaTex document in Atom. When I try to preview the PDF in a separate tab I get the error shown above and I cannot see the PDF in the separate tab. I can however open the full pdf on its own and it looks like things have compiled fine. I was using a book document type, but the error also occurred when using the article type.

**Comment by ashthespy** [comment] 2017-04-28 14:04
This error would indicate that Atom-LaTeX is having issues figuring out the root directory of your LaTeX project. So it shouldn't matter what document type you are compiling :-)

Back to some questions 
1. Can you share your atom-latex configuration from `config.cson` (found from the menu File -> Config..)
1. Can you share what your project folder looks like?  Do you have a `.latexcfg` file in the project root currently?

**Comment by jasm32851** [comment] 2017-04-28 14:16
This is my config.cson file:

"*":
  "atom-beautify":
    cpp:
      beautify_on_save: true
      configPath: "/usr/share/uncrustify/defaults.cfg"
    general:
      analytics: false
  core:
    autoHideMenuBar: true
    telemetryConsent: "limited"
    themes: [
      "one-light-ui"
      "one-light-syntax"
    ]
  editor:
    atomicSoftTabs: false
    fontSize: 13
    invisibles: {}
    scrollPastEnd: true
    showIndentGuide: true
    softTabs: false
    softWrapHangingIndent: 4
  "exception-reporting":
    userId: "193766ad-0145-4ad3-b8ee-827b3a3db95d"
  "spell-check":
    grammars: [
      "source.asciidoc"
      "source.gfm"
      "text.git-commit"
      "text.plain"
      "text.plain.null-grammar"
      "text.tex.latex"
    ]
  "tree-view":
    hideVcsIgnoredFiles: true

This is what my project directory looks like:
 20 -rw-rw-r-- 1 james james  12441 Apr 28 08:13 manual_v1.fdb_latexmk
 36 -rw-rw-r-- 1 james james  30957 Apr 28 08:13 manual_v1.log
 12 -rw-rw-r-- 1 james james   6491 Apr 28 08:13 manual_v1.synctex.gz
128 -rw-rw-r-- 1 james james 124961 Apr 28 08:13 manual_v1.pdf
 16 -rw-rw-r-- 1 james james  11677 Apr 28 08:13 manual_v1.fls
  8 -rw-rw-r-- 1 james james   1247 Apr 28 08:13 manual_v1.aux
  8 -rw-rw-r-- 1 james james    509 Apr 28 08:13 manual_v1.toc
  8 -rw-rw-r-- 1 james james    938 Apr 27 15:53 manual_v1.tex


I do not have a latexcfg in my project directory. Thanks for your quick
response!

-James

**Comment by ashthespy** [comment] 2017-04-28 15:08
Looks like you have the default Atom-LaTeX config.

It would seem like your issue is different, as the original issue's stack trace is from the "Delay refresh actions of atom-minimap" setting, but you don't seem to have that setting on. 

To confirm, you are able to build the document fine, but you get this error when you use the "Preview PDF" button from the bottom panel after building? Could you provide your actual error, along with how to reproduce it when it happens the next time?

**Comment by jasm32851** [comment] 2017-04-28 15:09
Here is the error:

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [atom-latex](https://github.com/James-Yu/Atom-LaTeX)
package 0.7.7


### Stack Trace

Uncaught TypeError: Cannot read property 'file' of undefined

```
At /home/james/.atom/packages/atom-latex/lib/manager.coffee:88

TypeError: Cannot read property 'file' of undefined
    at Manager.module.exports.Manager.findMainSelfMagic
(/packages/atom-latex/lib/manager.coffee:88:5)
    at Manager.module.exports.Manager.findMainSequence
(/packages/atom-latex/lib/manager.coffee:65:21)
    at Manager.module.exports.Manager.findMain
(/packages/atom-latex/lib/manager.coffee:42:15)
    at Server.module.exports.Server.httpHandler
(/packages/atom-latex/lib/server.coffee:33:26)
    at /packages/atom-latex/lib/server.coffee:12:46)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:543:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
```

### Commands

```
 15x -2:22.4.0 core:backspace (input.hidden-input)
 51x -1:59.7.0 core:move-right (input.hidden-input)
     -1:57.3.0 core:move-left (input.hidden-input)
     -1:25.1.0 find-and-replace:show (input.hidden-input)
     -1:21.5.0 core:confirm (input.hidden-input)
 14x -1:19.3.0 find-and-replace:find-next (input.hidden-input)
     -1:03.1.0 find-and-replace:show (input.hidden-input)
 11x -1:01.6.0 find-and-replace:find-next (input.hidden-input)
     -0:04.9.0 atom-latex:preview-tab (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.23
atom-latex 0.7.7
multi-cursor 2.1.5
pdf-view 0.57.0
```

**Comment by ashthespy** [comment] 2017-04-28 15:30
Now we are getting somewhere! 
Do you set your [root file](https://github.com/James-Yu/Atom-LaTeX#setting-the-latex-root-file) via Magic Tex command? 
It would seem that the file path set there doesn't exist, throwing this error

**Comment by jasm32851** [comment] 2017-04-28 16:25
Ok I did not. I just went back and read the instructions on the root file
and created the following root file. I can now see the PDF preview in an
adjacent tab, but I still get the error shown below.

.latexcfg:
{ "root" : "/home/james/Dropbox/projects/SHCI_manual/manual_v1.tex" }

Error:

Uncaught Error: Could not call remote function 'getTitle'. Check that the
function signature is correct. Underlying error: Object has been destroyed
Error: Could not call remote function 'getTitle'. Check that the function
signature is correct. Underlying error: Object has been destroyed at
callFunction
(/usr/share/atom/resources/electron.asar/browser/rpc-server.js:226:11) at
EventEmitter.(/usr/share/atom/resources/electron.asar/browser/rpc-server.js:307:5)
at emitMany (events.js:127:13) at EventEmitter.emit (events.js:201:7) at
WebContents.(/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:222:13)
at emitTwo (events.js:106:13) at WebContents.emit (events.js:191:7)

Thanks,
James

**Comment by ashthespy** [comment] 2017-05-01 14:38
You don't necessary have to set the `.latexcfg` file,  a proper magic TeX command should also suffice. 

The issue you have just posted, does it occur when you you don't use split panes, but a single pane with two tabs?

**Comment by jasm32851** [comment] 2017-05-01 15:48
It happens when I use the command "Preview PDF in new tab." There are two
panes one with the preview and one with the tex document.

-James

**Comment by ashthespy** [comment] 2017-05-01 16:32
Could I request you to create a new issue via the error pop-up? 
I'll close this issue, and we can continue there.

**Closed by ashthespy** 2017-05-01 16:32 UTC

**Comment by dionyziz** [comment] 2018-01-03 22:47
I'm also getting this issue. Could you please link to the issue in which this was finally resolved?

**Comment by ashthespy** [comment] 2018-01-06 05:43
@dionyziz Could you share a stack trace?

**Comment by arturgomes** [comment] 2018-02-08 10:04
Hi there, I'm also having the same problem. I'm using Ubuntu 17.04, Atom 1.23.3 x64.

I have no .latexcfg file...
Stack Trace:

/home/artur/.atom/packages/atom-latex/lib/manager.coffee:111
Hide Stack Trace
TypeError: Cannot read property 'file' of undefined
    at Manager.module.exports.Manager.findMainSelfMagic (/home/artur/.atom/packages/atom-latex/lib/manager.coffee:111:5)
    at Manager.module.exports.Manager.findMainSequence (/home/artur/.atom/packages/atom-latex/lib/manager.coffee:80:23)
    at Manager.module.exports.Manager.findMain (/home/artur/.atom/packages/atom-latex/lib/manager.coffee:54:15)
    at Builder.module.exports.Builder.build (/home/artur/.atom/packages/atom-latex/lib/builder.coffee:12:24)
    at HTMLElement.disposables.add.atom.commands.add.atom-latex:build-here (/home/artur/.atom/packages/atom-latex/lib/main.coffee:34:53)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:388:36)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1393:34)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)

**Comment by ashthespy** [comment] 2018-02-08 11:36
@arturgomes  The issue pops up when your editor isn't selected as the active item. I have pushed a fix, which you can test:
```diff
diff --git a/lib/manager.coffee b/lib/manager.coffee
index 2f3b6e6..70c9c1b 100644
--- a/lib/manager.coffee
+++ b/lib/manager.coffee
@@ -94,8 +94,8 @@ class Manager extends Disposable

   findMainSelf: ->
     docRegex = /\\begin{document}/
-    editor = atom.workspace.getActiveTextEditor()
-    currentPath = editor?.getPath()
+    editor = atom.workspace.getActivePaneItem()
+    currentPath = editor?.buffer.file?.path
     currentContent = editor?.getText()

     if currentPath and currentContent
@@ -107,8 +107,8 @@ class Manager extends Disposable

   findMainSelfMagic: ->
     magicRegex = /(?:%\s*!TEX\sroot\s*=\s*([^\s]*\.tex)$)/m
-    editor = atom.workspace.getActiveTextEditor()
-    currentPath = editor?.getPath()
+    editor = atom.workspace.getActivePaneItem()
+    currentPath = editor?.buffer.file?.path
     currentContent = editor?.getText()

     if currentPath and currentContent
```

Or, you can just make the text editor active, and then use the menu to build until the update is published. :-)

**Comment by arturgomes** [comment] 2018-02-08 11:40
Dear @ashthespy, thank you very much. It works like a charm!
