### ISSUE TITLE
Uncaught Error: watch ~/Documentos/Estudios/uned/mat/c1/algebra I/apuntes - resumenes ENOSPC

### ISSUE THREAD

**Issue by AlxG78** [James-Yu/Atom-LaTeX#121] opened 2017-10-26 14:17 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: linux 4.9.56-1-lts
**Thrown From**: [atom-latex](https://github.com/James-Yu/Atom-LaTeX) package 0.8.2

### Stack Trace

Uncaught Error: watch /home/pepe/Documentos/Estudios/uned/mat/c1/algebra I/apuntes - resumenes ENOSPC

```
At events.js:160

Error: watch /home/pepe/Documentos/Estudios/uned/mat/c1/algebra I/apuntes - resumenes ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1316:19)
    at Object.fs.watch (fs.js:1341:11)
    at createFsWatchInstance (/packages/atom-latex/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/packages/atom-latex/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/packages/atom-latex/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/packages/atom-latex/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at /packages/atom-latex/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at /packages/atom-latex/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
     -5:25.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -0:30.1.0 intentions:highlight (input.hidden-input)
     -0:29.6.0 tree-view:toggle (input.hidden-input)
     -0:26.4.0 intentions:highlight (input.hidden-input)
     -0:25.5.0 atom-latex:build (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
atom-alignment 0.13.0 
atom-beautify 0.30.5 
atom-clock 0.1.15 
atom-css-comb 3.3.1 
atom-html-preview 0.2.2 
atom-latex 0.8.2 
atom-terminal 0.8.0 
autoclose-html 0.23.0 
autocomplete-cmake 0.3.1 
autocomplete-ctags 0.4.1 
autocomplete-json 5.5.0 
autocomplete-modules 1.7.3 
autocomplete-paths 2.12.1 
autocomplete-python 1.10.3 
autocomplete-xml 0.9.4 
build 0.69.0 
build-cmake 0.11.0 
busy 0.7.0 
busy-signal 1.4.3 
color-picker 2.2.5 
css-snippets 1.1.0 
date 2.0.3 
docblockr 0.11.0 
editorconfig 2.2.2 
emmet 2.4.3 
ex-mode 0.18.0 
file-icons 2.1.13 
gcc-make-run 0.2.12 
highlight-selected 0.13.1 
Hydrogen 2.0.1 
indent-detective 0.1.1 
ink 0.7.7 
intentions 1.1.5 
javascript-snippets 1.2.1 
julia-client 0.6.4 
jupyter-notebook 0.0.10 
language-cmake 0.3.0 
language-gherkin-i18n 1.3.4 
language-gnuplot-atom 0.2.0 
language-julia 0.12.0 
language-latex 1.1.1 
latex 0.48.0 
latex-autocomplete 1.0.0 
latex-completions 0.3.3 
latexer 0.3.0 
latextools 0.8.5 
linter 2.2.0 
linter-chktex 1.3.1 
linter-gcc 0.7.1 
linter-julia 0.7.2 
linter-markdown 5.2.0 
linter-python-pep8 0.2.0 
linter-spell 0.15.0 
linter-spell-html 0.7.0 
linter-spell-latex 0.10.0 
linter-ui-default 1.6.10 
markdown-pdf 2.1.0 
markdown-preview-enhanced 0.14.11 
markdown-preview-plus 2.4.16 
markdown-writer 2.7.3 
minimap 4.29.7 
open-recent 5.0.0 
pdf-view 0.59.0 
pigments 0.40.2 
preview-inline 1.4.7 
python-debugger 0.2.0 
python-tools 0.6.9 
remote-edit 1.9.0 
script 3.17.3 
seti-ui 1.9.0 
split-diff 1.5.1 
symbols-tree-view 0.14.0 
tasks 2.6.7 
todo-show 2.1.0 
tool-bar 1.1.0 
uber-juno 0.1.2 
vim-mode 0.66.0 
```

**Comment by ashthespy** [comment] 2017-10-27 09:59
The `ENOSPC` error is an out of space error. Is your project folder extremely large?  Could you share details of what is in the folder `/home/pepe/Documentos/Estudios/uned/mat/c1/algebra I/apuntes - resumenes`

**Comment by ByteHamster** [comment] 2017-11-04 13:53
Same error here. The document compiles, but I am flooded with errors, for example:

> Uncaught Error: watch /xyz/02/2.fls ENOSPC

> Uncaught Error: watch /xyz/02/2.fdb_latexmk ENOSPC

> Uncaught Error: watch /xyz/02/2.synctex(busy) ENOSPC

Files in my project folder:

```
2.aux  2.fdb_latexmk  2.fls  2.log  2.nav  2.out 
2.pdf  2.pdfpc  2.snm  2.synctex.gz  2.tex  2.toc
```

There are some more files that are included using `\input`. Last week I compiled the same file without errors. Because there has not been an update of `Atom-LaTeX`, I suspect a system update broke something.

@AlxG78 are you using ArchLinux, too?

**Comment by AlxG78** [comment] 2017-11-05 10:23
Ye, I am using ArchLinux

**Comment by ByteHamster** [comment] 2017-11-07 10:53
Thanks, that seems to be the reason. I can no longer reproduce the issue after increasing the watch limit

**Comment by ashthespy** [comment] 2017-11-07 11:00
I'm glad it's working - but you should look into the real issue increasing the watch limit is treating the symptom ;-) 
Were you able identify what is using up all your notifiers? If it's not Atom-LaTeX, I shall close this issue and let you investigate more..

**Comment by ByteHamster** [comment] 2017-11-07 11:13
I think I had opened Intellij while the error occurred. Intellij also complained about the watch limit (big project with a lot of files), but I did not realize that this could also be the problem in Atom-LaTeX. Intellij already complained before installing Atom-LaTeX

Let's see if @AlxG78 can fix it before closing

**Comment by ashthespy** [comment] 2017-11-17 09:28
Closing this issue, @AlxG78 feel free to comment if you are still facing issues.

**Closed by ashthespy** 2017-11-17 09:28 UTC
Labels: more-info-needed
