### ISSUE TITLE
BibTex shouldn't fail if there's no .bib file

### ISSUE THREAD

**Issue by Chais** [James-Yu/Atom-LaTeX#19] opened 2017-03-11 13:50 UTC
I'm compiling a document with the custom toolchain and BibTex keeps failing with `Command failed: bibtex <filename>`. The document compiles fine, but this results in it not being previewed. I guess it would be good to not run BibTex if there's nothing to run it on.

**Comment by James-Yu** [comment] 2017-03-11 15:09
Duplicate of #14 #15

**Closed by James-Yu** 2017-03-11 15:09 UTC
