### ISSUE TITLE
Slow autocomplete on large documents

### ISSUE THREAD

**Issue by dpo** [James-Yu/Atom-LaTeX#146] opened 2018-04-03 10:19 UTC
I have a LaTeX document of about 3,000 lines and I'm seeing a very noticeable delay every time I type a backslash that seems due to autocompletion. Disabling this package makes the delay go away (along with all the other useful features!) I tried starting a new LaTeX document and I don't observe the delay, which makes me think that the file length has something to do in the matter. Do you have any idea what could be causing this and how to make the delay go away? I'm willing to forgo certain autocompletions to make it go away. Thanks.

**Comment by ashthespy** [comment] 2018-04-12 09:49
Hi,
can you give me some more information on the situation? Have you by any chance disabled the file watcher? The autocomplete only parses the file the on the first `\` and then watches the files for changes, instead of the earlier behaviour of parsing the file on each `\` press. 
Unfortunately this seems to be a system/configuration depended issue, as I can't seem to reproduce it here. But, more than willing to go bug hunting with you!

**Comment by dpo** [comment] 2018-04-12 10:10
Thank you for your reply! I'm not sure what the file watcher is. I don't see a setting for it in atom-latex?!

**Comment by ashthespy** [comment] 2018-04-12 10:27
Its on by default, unless you have a `disable_watcher` set in your `config.cson`.  Do you have anything interesting in the debug console when the lag appears? I am afraid, its a hit or miss for me going by the information I have right now!

**Comment by dpo** [comment] 2018-04-12 11:10
I didn't disable it in `config.cson`. Although nothing appears in the console when I hit `\`, I did notice a bunch of the messages you mention in https://github.com/atom/autocomplete-plus/issues/948 when I opened it. So perhaps the issue is related somehow. I'm surprised you can't reproduce it. Disabling autocomplete-plus makes the lag go away (along with completion, of course). Thanks for the help so far anyways!

**Comment by dpo** [comment] 2018-04-12 11:35
I observe the same issue in my large file (including the console messages), but not in a new (short) TeX document (possibly because there are few/no autocomplete suggestions).

**Comment by ashthespy** [comment] 2018-04-23 08:50
@dpo  Any improvements now that https://github.com/atom/bracket-matcher/pull/346 has been merged?

**Comment by SiriusStarr** [comment] 2018-05-09 18:14
I'm having this same issue.  Typing \ causes a lag of about 4-5 seconds before autocomplete pops up, other than that everything is snappy.  The only thing that shows up in my console is:
`[Violation] 'textInput' handler took 4434ms`
(obviously the listed delay varies between 4-5k ms) unless I'm looking in the wrong place for debug info.  The problem isn't there on a minimal LaTeX document but is horribly annoying on the decent sized one I'm trying to work on (5k lines, 600kB).  Obviously problem goes away with autocomplete-plus disabled (along with autocompletion).  What can I do to help track down the root cause of this?

**Comment by ashthespy** [comment] 2018-08-31 12:04
@dpo @SiriusStarr Is this still issue still persistent with the new [`autocomplete-plus` fixes](https://github.com/atom/autocomplete-plus/pull/984)?

**Comment by dpo** [comment] 2018-09-12 00:15
@ashthespy It's hard to say. I've since split my long document into several smaller ones, so I can't really test the issue on a real use case at the moment. Many thanks for your constant attention to this package though!

**Comment by ashthespy** [comment] 2018-09-12 09:19
Hmm, okay - I shall close this issue for now then. I am keeping track of the upstream issue, but if you start facing issues again, please nudge this issue along.

**Closed by ashthespy** 2018-09-12 09:19 UTC
