### ISSUE TITLE
\cite autocompletion

### ISSUE THREAD

**Issue by SHWB** [James-Yu/Atom-LaTeX#6] opened 2017-02-20 14:53 UTC
Hi, 
I can't get any suggestion after typing a \cite command.

I followed all the steps in the Requirements section.
This is a gist with a MWE, where the bib file and the main are in the same folder.

https://gist.github.com/anonymous/59292e9b8aa1d214fa75cc27107a8add

I tried several combinations, as adding a TEX root header to the bib files as well.
Originally, I faced this problem with .bib files in a different subfolder, so I set up the attached example, but the autocompletion does not trigger even with a .bib file in the same folder.

Thanks.

**Comment by James-Yu** [comment] 2017-02-20 14:58
Thank you for the issue and self-explained gist. Currently only \bibliography is detected as a valid bib definition. I will add support to \addbibresource shortly.

**Comment by James-Yu** [comment] 2017-02-20 15:04
New v`0.5.5` should fix this problem. If not, please re-open this issue.

**Comment by SHWB** [comment] 2017-02-20 15:17
Thank you for being so quickly responsive, however the issue appears not to be fixed.

**Comment by James-Yu** [comment] 2017-02-20 15:34
v`0.5.6` should fix the problem. The bug is caused by a missing `\.` identifier in the regex to identify bibtex file names, which causes files with extensions ignored by the editor. The bug is fixed now. Please test and see if the issue persists.

**Comment by SHWB** [comment] 2017-02-20 15:44
No problem at all! 
Now it works fine if the bib file is in the root folder. 

I tried the following `\addbibresource{bib/mybib.bib}` in the MWE working example as above (paths changed accordingly), but no pop-up.

**Comment by James-Yu** [comment] 2017-02-20 15:45
Shoot, I forgot to also add `\/\\` to the regex. Will do so in the next version.

**Comment by James-Yu** [comment] 2017-02-21 00:58
v`0.5.7` should FINALLY fix the problem. :-]

**Closed by James-Yu** 2017-02-21 00:58 UTC
