### ISSUE TITLE
Uncaught Error: watch ~/Documentos/Estudios/uned/mat/c1/algebra I ENOSPC

### ISSUE THREAD

**Issue by AlxG78** [James-Yu/Atom-LaTeX#123] opened 2017-10-28 06:47 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: linux 4.9.56-1-lts
**Thrown From**: [atom-latex](https://github.com/James-Yu/Atom-LaTeX) package 0.8.2

### Stack Trace

Uncaught Error: watch /home/pepe/Documentos/Estudios/uned/mat/c1/algebra I ENOSPC

```
At events.js:160

Error: watch /home/pepe/Documentos/Estudios/uned/mat/c1/algebra I ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1316:19)
    at Object.fs.watch (fs.js:1341:11)
    at createFsWatchInstance (/packages/atom-latex/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/packages/atom-latex/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/packages/atom-latex/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/packages/atom-latex/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at /packages/atom-latex/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at /packages/atom-latex/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
     -3:11.2.0 core:move-left (input.hidden-input)
     -3:10.6.0 intentions:highlight (input.hidden-input)
     -3:09.7.0 core:paste (input.hidden-input)
  4x -2:59.4.0 core:delete (input.hidden-input)
     -2:39.8.0 intentions:highlight (input.hidden-input)
     -2:39.3.0 core:copy (input.hidden-input)
     -2:35.4.0 intentions:highlight (input.hidden-input)
     -2:35.1.0 core:paste (input.hidden-input)
     -0:39.5.0 atom-latex:tools-dollarsign (input.hidden-input)
     -0:38.2.0 core:move-right (input.hidden-input)
     -0:34.5.0 atom-latex:tools-dollarsign (input.hidden-input)
     -0:33.1.0 core:move-right (input.hidden-input)
     -0:18.4.0 atom-latex:tools-dollarsign (input.hidden-input)
     -0:11.4.0 markdown-writer:indent-list-line (input.hidden-input)
     -0:11.4.0 docblockr:parse-tab (input.hidden-input)
     -0:11.4.0 autocomplete-plus:confirm (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
atom-alignment 0.13.0 
atom-beautify 0.30.5 
atom-clock 0.1.15 
atom-css-comb 3.3.1 
atom-html-preview 0.2.2 
atom-latex 0.8.2 
atom-terminal 0.8.0 
autoclose-html 0.23.0 
autocomplete-cmake 0.3.1 
autocomplete-ctags 0.4.1 
autocomplete-json 5.5.0 
autocomplete-modules 1.7.3 
autocomplete-paths 2.12.1 
autocomplete-python 1.10.3 
autocomplete-xml 0.9.4 
build 0.69.0 
build-cmake 0.11.0 
busy 0.7.0 
busy-signal 1.4.3 
color-picker 2.2.5 
css-snippets 1.1.0 
date 2.0.3 
docblockr 0.11.0 
editorconfig 2.2.2 
emmet 2.4.3 
ex-mode 0.18.0 
file-icons 2.1.13 
gcc-make-run 0.2.12 
highlight-selected 0.13.1 
Hydrogen 2.0.1 
indent-detective 0.1.1 
ink 0.7.7 
intentions 1.1.5 
javascript-snippets 1.2.1 
julia-client 0.6.4 
jupyter-notebook 0.0.10 
language-cmake 0.3.0 
language-gherkin-i18n 1.3.4 
language-gnuplot-atom 0.2.0 
language-julia 0.12.0 
language-latex 1.1.1 
latex 0.49.0 
latex-autocomplete 1.0.0 
latex-completions 0.3.3 
latexer 0.3.0 
latextools 0.8.5 
linter 2.2.0 
linter-chktex 1.3.1 
linter-gcc 0.7.1 
linter-julia 0.7.2 
linter-markdown 5.2.0 
linter-python-pep8 0.2.0 
linter-spell 0.15.0 
linter-spell-html 0.7.0 
linter-spell-latex 0.10.0 
linter-ui-default 1.6.10 
markdown-pdf 2.1.0 
markdown-preview-enhanced 0.14.11 
markdown-preview-plus 2.4.16 
markdown-writer 2.7.3 
minimap 4.29.7 
open-recent 5.0.0 
pdf-view 0.59.0 
pigments 0.40.2 
preview-inline 1.4.7 
python-debugger 0.2.0 
python-tools 0.6.9 
remote-edit 1.9.0 
script 3.17.3 
seti-ui 1.9.0 
split-diff 1.5.1 
symbols-tree-view 0.14.0 
tasks 2.6.7 
todo-show 2.1.0 
tool-bar 1.1.0 
uber-juno 0.1.2 
vim-mode 0.66.0 
```

**Comment by ashthespy** [comment] 2017-10-28 09:55
Duplicate of #121 - please discuss there!

**Closed by ashthespy** 2017-10-28 09:55 UTC
