### ISSUE TITLE
Better notifications for errors while parsing citations 

### ISSUE THREAD

**Issue by cevers** [James-Yu/Atom-LaTeX#67] opened 2017-05-03 13:13 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [atom-latex](https://github.com/James-Yu/Atom-LaTeX) package 0.7.8

### Stack Trace

Uncaught TypeError: Cannot read property 'substring' of undefined

```
At /Users/cevers/.atom/packages/atom-latex/lib/autocomplete/citation.coffee:74

TypeError: Cannot read property 'substring' of undefined
    at Citation.module.exports.Citation.splitBibItem (/packages/atom-latex/lib/autocomplete/citation.coffee:74:16)
    at Citation.module.exports.Citation.getBibItems (/packages/atom-latex/lib/autocomplete/citation.coffee:51:21)
    at /packages/atom-latex/lib/manager.coffee:225:38)
    at emitTwo (events.js:106:13)
    at FSWatcher.emit (events.js:191:7)
    at /packages/atom-latex/node_modules/chokidar/index.js:191:15)
    at FSWatcher._emit (/packages/atom-latex/node_modules/chokidar/index.js:233:5)
    at /packages/atom-latex/node_modules/chokidar/lib/fsevents-handler.js:321:12)
    at /packages/atom-latex/node_modules/chokidar/lib/fsevents-handler.js:370:7)
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
     -1:39.7.0 atom-latex:build (input.hidden-input)
     -0:44.6.0 core:move-right (input.hidden-input)
     -0:38.6.0 core:backspace (input.hidden-input)
  3x -0:36.7.0 core:save (input.hidden-input)
  2x -0:27 core:move-left (input.hidden-input)
  3x -0:25.2.0 core:select-right (input.hidden-input)
  2x -0:22.5.0 core:save (input.hidden-input)
  3x -0:13.3.0 editor:newline (input.hidden-input)
     -0:11.5.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-latex 0.7.8 
autocomplete-bibtex 0.7.0 
project-manager 3.3.4 
```

**Comment by ashthespy** [comment] 2017-05-03 13:41
Hi,
Could you post the contents of the `.bib` file that you are using? 
The error would indicate that the there might be an item in your file with some syntax issues.

**Comment by ashthespy** [comment] 2017-05-09 11:18
Closing this, reopen if you feel the need!

**Comment by balandinodidonato** [comment] 2017-08-30 16:37
@ashthespy I keep having the same error. How can I fix that?

###Stack Trace

``` TypeError: Cannot read property 'substring' of undefined
    at Citation.module.exports.Citation.splitBibItem (/Users/balandinodidonato/.atom/packages/atom-latex/lib/autocomplete/citation.coffee:74:16)
    at Citation.module.exports.Citation.getBibItems (/Users/balandinodidonato/.atom/packages/atom-latex/lib/autocomplete/citation.coffee:51:21)
    at FSWatcher.<anonymous> (/Users/balandinodidonato/.atom/packages/atom-latex/lib/manager.coffee:275:34)
    at emitOne (events.js:96:13)
    at FSWatcher.emit (events.js:188:7)
    at FSWatcher.<anonymous> (/Users/balandinodidonato/.atom/packages/atom-latex/node_modules/chokidar/index.js:196:15)
    at FSWatcher._emit (/Users/balandinodidonato/.atom/packages/atom-latex/node_modules/chokidar/index.js:238:5)
    at FSWatcher.<anonymous> (/Users/balandinodidonato/.atom/packages/atom-latex/node_modules/chokidar/lib/fsevents-handler.js:204:14)
    at addOrChange (/Users/balandinodidonato/.atom/packages/atom-latex/node_modules/chokidar/lib/fsevents-handler.js:210:7)
    at /Users/balandinodidonato/.atom/packages/atom-latex/node_modules/chokidar/lib/fsevents-handler.js:216:35
    at FSReqWrap.oncomplete (fs.js:112:15)```

**Comment by ashthespy** [comment] 2017-08-30 16:47
Could you share your `.bib` file? Or better yet, can you recreate the issue with a minimal `.bib` file?

**Comment by balandinodidonato** [comment] 2017-08-30 16:54
Sure. See attached `.bib` file.

[references.bib.zip](https://github.com/James-Yu/Atom-LaTeX/files/1264421/references.bib.zip)

**Comment by ashthespy** [comment] 2017-08-30 17:34
Like I said there are syntax issues with the `.bib` file. 
In your case, you have an empty entry causing the error.
```
@article{Anonymous:NryDNnoe
}
```
 I wonder if the package should handle these cases, throwing a more friendly warning?

**Comment by balandinodidonato** [comment] 2017-08-30 17:49
Thanks.

> I wonder if the package should handle these cases, throwing a more friendly warning?

Yes, that's a good idea. It would be very helpful to have a more friendly message explaining what the issue is.

**Closed** 2017-08-31 10:51 UTC
Labels: enhancement
