### ISSUE TITLE
Tab Split right causes compilation failure

### ISSUE THREAD

**Issue by johschmitz** [James-Yu/Atom-LaTeX#84] opened 2017-07-24 13:19 UTC
When I do right-click `Split right` on a tab and have two latex files of my project opened next to each other, I can not use `Ctrl-s` to build. Instead I get various kinds of errors.

**Comment by ashthespy** [comment] 2017-07-25 00:05
Require more information, as I am unable to reproduce here!
What I tried was a simple multi file LaTeX project - `Split right` an file and then build on save option  with `Ctrl-s` to build and view output in a new tab 
it works quite well for me :-)

**Comment by johschmitz** [comment] 2017-07-25 00:11
Did you do ctrl-s on the right tab or on the left tab?

**Comment by ashthespy** [comment] 2017-07-25 00:14
Either works fine for me,
![testing_splitright](https://user-images.githubusercontent.com/16233271/28550089-eb028888-70de-11e7-8b65-029a7e7540fe.gif)

**Comment by johschmitz** [comment] 2017-07-25 13:26
I do `ctrl-s` in the left tab it works, I do `ctrl-s` in the right tab I get the following error
```
TypeError: Cannot read property 'match' of undefined
    at Parser.module.exports.Parser.parse (/home/schmitz/.atom/packages/atom-latex/lib/parser.coffee:23:11)
    at Builder.module.exports.Builder.postBuild (/home/schmitz/.atom/packages/atom-latex/lib/builder.coffee:90:19)
    at Builder.module.exports.Builder.buildProcess (/home/schmitz/.atom/packages/atom-latex/lib/builder.coffee:47:8)
    at /home/schmitz/.atom/packages/atom-latex/lib/builder.coffee:63:12
    at ChildProcess.exithandler (child_process.js:209:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

**Comment by ashthespy** [comment] 2017-08-03 09:49
Ah - this seems to be related to #78. I shall look into it when I get some time :-)

**Comment by ashthespy** [comment] 2017-08-28 08:42
Closing this, please comment if you have more info!

**Closed by ashthespy** 2017-08-28 08:42 UTC
Labels: more-info-needed
